In [1]:
import numpy as np
from sklearn import svm,metrics,preprocessing

In [2]:
data=np.load('data_embedded.npy')
label=np.load('label.npy')

In [3]:
# Normalizer
# in_encoder = preprocessing.Normalizer(norm='l2')
# X = in_encoder.transform(data)

In [4]:
out_encoder = preprocessing.LabelEncoder()
out_encoder.fit(label)
Y = out_encoder.transform(label)

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(data,Y,test_size=0.25)

In [6]:
model = svm.SVC(kernel='linear')
model.fit(X_train, Y_train)

SVC(kernel='linear')

In [7]:
Y_pred = model.predict(X_test)

In [8]:
score_test = metrics.accuracy_score(Y_test, Y_pred)

In [9]:
score_test*100

98.4375

In [10]:
Y_pred

array([ 6,  6,  1,  3,  6,  9, 11, 11,  9, 12,  6, 11, 11, 11,  9,  6, 11,
        6, 11,  6,  7, 11, 11, 10, 12, 11,  6,  2, 11, 11,  9, 11,  5, 12,
        6,  6,  3, 11,  2,  6,  6, 12,  4, 11,  6,  2,  6, 11,  1, 11,  7,
        3,  6,  6,  8, 11,  6,  6,  6,  6, 11,  6,  8,  8], dtype=int64)

In [11]:
Y_test

array([ 6,  6,  1,  3,  6,  9, 11, 11,  9, 12,  6, 11, 11, 11,  9,  6, 11,
        6, 11,  6,  7, 11, 11, 10, 12, 11,  6,  2, 11, 11,  9, 11,  5, 12,
        6,  6,  3, 11,  2,  6,  6, 12,  4, 11,  6,  2,  6, 11,  1, 11,  7,
        3,  6,  6,  8, 11,  6,  6, 11,  6, 11,  6,  8,  8], dtype=int64)

In [12]:
import joblib

joblib_file = "svm_model.pkl"
joblib.dump(model, joblib_file)

['svm_model.pkl']

In [13]:
out_encoder

LabelEncoder()

In [14]:
predict_names = out_encoder.inverse_transform(Y_pred)

In [15]:
predict_names

array(['Minh', 'Minh', 'Aubameyang', 'Leno', 'Minh', 'Tierney', 'Unknown',
       'Unknown', 'Tierney', 'Xhaka', 'Minh', 'Unknown', 'Unknown',
       'Unknown', 'Tierney', 'Minh', 'Unknown', 'Minh', 'Unknown', 'Minh',
       'Pepe', 'Unknown', 'Unknown', 'Torreira', 'Xhaka', 'Unknown',
       'Minh', 'Bellerin', 'Unknown', 'Unknown', 'Tierney', 'Unknown',
       'Mesut Ozil', 'Xhaka', 'Minh', 'Minh', 'Leno', 'Unknown',
       'Bellerin', 'Minh', 'Minh', 'Xhaka', 'Luiz', 'Unknown', 'Minh',
       'Bellerin', 'Minh', 'Unknown', 'Aubameyang', 'Unknown', 'Pepe',
       'Leno', 'Minh', 'Minh', 'Sokratis', 'Unknown', 'Minh', 'Minh',
       'Minh', 'Minh', 'Unknown', 'Minh', 'Sokratis', 'Sokratis'],
      dtype='<U14')

In [16]:
Y

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,
        7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11